# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PostListApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PostListApp

  target 'PostListAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PostListApp-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PostListApp-tvOS

  target 'PostListApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end